### ISSUE TITLE
Requests generated through Media Pipeline is not using scrapy-impersonate download handler

### ISSUE THREAD

**Issue by Ehsan-U** [jxlil/scrapy-impersonate#6]
Lets suppose this website:
afdb.org/en/

The standard requests getting 200 Status but Files are getting 403 because Media pipeline is not using impersonate handler.

**Comment by jxlil** [comment]
Hi @Ehsan-U 

It's necessary to set the `impersonate` key in [Request.meta](https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request.meta) so that `ImpersonateDownloadHanlder` can handle the request, otherwise the request will be handled by the native Scrapy downloader.

In the case of `FilesPipeline`/`ImagesPipeline` it's required to override the [`get_media_requests`](https://github.com/scrapy/scrapy/blob/a5da77d01dccbc91206d053396fb5b80e1a6b15b/scrapy/pipelines/files.py#L542C1-L545C64) function:
```python
class CustomFilesPipeline(FilesPipeline):
     def __init__(self, store_uri, download_func=None, settings=None):
         super().__init__(store_uri, download_func, settings)

     def get_media_requests(self, item, info):
         urls = ItemAdapter(item).get(self.files_urls_field, [])
         return [Request(u, callback=NO_CALLBACK, meta={"impersonate": "chrome110"}) for u in urls]
```

This way the Requests now include the `impersonate` key and will be handled by the `ImpersonateDownloadHandler` downloader.

**Comment by Ehsan-U** [comment]
Thanks for the response, @jxlil

I've observed that requests generated from the media pipeline are downloaded directly by the `Engine`. Recently, I noticed that the dupefilter doesn't seem to apply to media requests. I reached out to the Scrapy devs, and they confirmed that this behavior is expected. So, just to clarify, are you certain that `ImpersonateDownloadHandler` will be used to handle these media requests?

**Comment by Ehsan-U** [comment]
still this `curl` error appearing for some files, not all

`2024-05-02 04:02:25 [crawler.pipelines] WARNING: File (unknown-error): Error downloading file from <GET https://cites.org/sites/default/files/i/CITES_WWD_Brochure2014.pdf> referred in <None>: Failed to perform, curl: (55) Send failure: Connection reset by peer. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.`

**Comment by jxlil** [comment]
That error is related to [curl_cffi](https://github.com/yifeikong/curl_cffi). Open an issue in that project
